### PR TITLE
DOCS-1367: 12.0 screenshot review

### PR DESCRIPTION
**Pull request by q5sys**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by Mrt134** [comment]
Please add the Jira ticket number to the PR title in the future so the integration can do its thing, thanks!

**Comment by q5sys** [comment]
ive been doing that, guess I forgot on this one.  Branch is named for the ticket, at least I remembered that. lol

**Review by Mrt134 — CHANGES_REQUESTED** [review]
Went through the image list and site preview page by page and found a few things to update:

Images _TN-12.0-encryption-1.png_, _fusion-pool-create.png_ shows errors on the pool creation screen and don't demonstrate a valid pool creation scenario. Is this intentional? Additionally, TN-12.0-encryption-1.png could show having the Encryption checkbox set.

Does the shot of System > General in /hub/initial-setup/security/best-practices/manage-tls/ need to be replaced?

Zvol creation image in /hub/initial-setup/storage/zvols/ needs to be replaced.

The image in /hub/initial-setup/storage/fusion-pool/ doesn't appear to be getting updated.

The third image in /hub/tasks/scheduled/replication/local/ doesn't appear to be getting updated.

Images in /hub/tasks/advanced/jails/#additional-storage aren't getting updated.

**Comment by q5sys** [comment]
I'll go back through and check each of these

**Comment by q5sys** [comment]
> Images TN-12.0-encryption-1.png, fusion-pool-create.png shows errors on the pool creation screen and don't demonstrate a valid pool creation scenario. Is this intentional? Additionally, TN-12.0-encryption-1.png could show having the Encryption checkbox set.

The error was intentional to show that they cant be mixed types, but I forgot to move the image to a more appropriate spot in the page.  I can undo if you want. 
To do so, I just need to change the image from fusion-pool-create.png to 12.0-fusion-pool-create.PNG

> Does the shot of System > General in /hub/initial-setup/security/best-practices/manage-tls/ need to be replaced?

md file had wrong image name. fixed

> Zvol creation image in /hub/initial-setup/storage/zvols/ needs to be replaced.

md file had wrong image name. fixed

> The image in /hub/initial-setup/storage/fusion-pool/ doesn't appear to be getting updated.

md file had wrong image name. fixed

> The third image in /hub/tasks/scheduled/replication/local/ doesn't appear to be getting updated.

Fixed

> Images in /hub/tasks/advanced/jails/#additional-storage aren't getting updated.

Yup, I missed those two shots completely. fixed

**Comment by Mrt134** [comment]
> The error was intentional to show that they cant be mixed types, but I forgot to move the image to a more appropriate spot in the page. I can undo if you want.

I'm fine with showing the error for mixed types, just want to be sure that the image is in the right spot :)

**Review by Mrt134 — APPROVED** [review]
Looks good! I edited a couple spots to clean extraneous whitespace/empty lines, but the new images look great. Good job!

**Pull request merged**
