### PR TITLE
DOCS-1256: TrueNAS Glossary

### PR DESCRIPTION
**Pull request by q5sys**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by Mrt134** [comment]
Similar to the Field Reference Guide, I'll do a review and set up the file with a few organizational elements and sync with @q5sys about it.

**Comment by Mrt134** [comment]
It's a great start, but I think we can build out a little more, maybe with Sharing, Virtualization, Directory Services, and other categories we can pull terms and concepts out of the UI and define here in the glossary.

**Review by Mrt134 — CHANGES_REQUESTED** [review]
additional buildout is needed

**Comment by q5sys** [comment]
> It's a great start, but I think we can build out a little more, maybe with Sharing, Virtualization, Directory Services, and other categories we can pull terms and concepts out of the UI and define here in the glossary.

@Mrt134  Do you have any ideas of what you want added?  I already have the items from Directory Services defined (AD, LDAP, NIS, Kerberos).  As for sharing I've already got most of that defined (NFS, SMB, Webdav, iscsi). I did miss FTP so I can add that, but what else would you like added?  As for Virtualization, not sure what to put under that outside of defining terms like CPU, Memory, etc.

**Comment by Mrt134** [comment]
Please review the TrueNAS CORE, SCALE, and Enterprise UIs (just the additional screens unlocked by an Enterprise license, like enclosure management) screen by screen and look for any additional acronyms, concepts, or terminology that the UI assumes knowledge on the part of the user. List any new items you've found and I'll work with you to organize. Thanks!

**Comment by q5sys** [comment]
> Please review the TrueNAS CORE, SCALE, and Enterprise UIs (just the additional screens unlocked by an Enterprise license, like enclosure management) screen by screen and look for any additional acronyms, concepts, or terminology that the UI assumes knowledge on the part of the user. List any new items you've found and I'll work with you to organize. Thanks!

Ah yea, good catch. I didn't think about Enterprise UI features.   Any ideas you can come up with to better organize everything are definitely welcome.

**Review by Mrt134 — APPROVED** [review]

**Pull request merged**
