### PR TITLE
Add reference info about dedup.

### PR DESCRIPTION
**Pull request by stilez**
It's a popular topic and question, but little is said in the guide at the moment. This fixes it.

### CODE REVIEW

**Comment by stilez** [comment]
Probably needs some refining, not sure how much or what. Please do whatever you think's needed. Thank you.

**Comment by Mrt134** [comment]
ok to test

**Comment by Mrt134** [comment]
retest this please

**Review by BonnieF — CHANGES_REQUESTED** [review]
The "If deduplication is used in an inadequately built system, the following symptoms may be seen:" table has one sentence that needs a period ("The system must perform disk I/O to fetch DDT entries, but these are usually 4K I/O and the underlying disk hardware is unable to cope in a timely manner")
I would also suggest that sentences in the Issues area of that table should end in a period
Also possibly the topic headings (like Deduplication on ZFS) should be formatted ## instead of #

**Review by BonnieF — DISMISSED** [review]

**Comment by stilez** [comment]
Done various small cleanup. Nothing big - also added some crosslinks to other hub pages, and moved 2 paragraphs to warnings.

**Comment by stilez** [comment]
Done various small cleanup. Nothing big - also added some crosslinks to other hub pages, and moved 2 paragraphs to warnings.

@BonnieF - It's about there now, I think.

**Comment by stilez** [comment]
Done various small cleanup. Nothing big - also added some crosslinks to other hub pages, and moved 2 paragraphs to warnings.

@BonnieF - It's about there now, I think.  Are you comfortable with me adding the 2 "resource" links? Disclosure: they are resources I wrote;  it seems as if I'm the forum go-to on dedup and SSDs ;-)

**Comment by stilez** [comment]
Done various small cleanup. Nothing big - also added some crosslinks to other hub pages, and moved 2 paragraphs to warnings.

@BonnieF - It's about there now, I think.  Are you comfortable with me adding the 2 "resource" links? Disclosure: they are resources I wrote;  it seems as if I'm the forum go-to on dedup and SSDs ;-)

**Review by BonnieF — APPROVED** [review]
fixed some syntax and it looks great!

**Comment by BonnieF** [comment]
The DOCS ticket for this is DOCS-1601

**Comment by stilez** [comment]
@BonnieF - Thanks. One favour, can you push some commits to ensure this is linked from any pages you think it helpful to users? (ZFS primer, storage, creating basic pool, advancedd magic)

**Comment by BonnieF** [comment]
Hey @stilez 
I went ahead and created a DOCS ticket to remind me to set up the links after this pr is merged. Thank you

**Pull request merged**
