### PR TITLE
DOCS-733 Switch to google search on site.

### PR DESCRIPTION
**Pull request by a-stjohn**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by Mrt134** [comment]
Tried the preview and searched "Active Directory" - the first result was the french version of the AD article, and couldn't find the English version of that article in the first page of results - is there a way to tune the search results to only the currently active language?

**Comment by a-stjohn** [comment]
> Tried the preview and searched "Active Directory" - the first result was the french version of the AD article, and couldn't find the English version of that article in the first page of results - is there a way to tune the search results to only the currently active language?

Not really sure if there's a way around it, because most of our "french" articles are in English. It's simply searching the docs site (and it's structure). I think when the site is fully translated, it won't be pulling the French part of the site.

**Comment by q5sys** [comment]
> > Tried the preview and searched "Active Directory" - the first result was the french version of the AD article, and couldn't find the English version of that article in the first page of results - is there a way to tune the search results to only the currently active language?
> 
> Not really sure if there's a way around it, because most of our "french" articles are in English. It's simply searching the docs site (and it's structure). I think when the site is fully translated, it won't be pulling the French part of the site.

Tim, this is what I mentioned weeks ago that was going to happen with the new way we decided to do languages.  The only way around this is to block all the languages from crawling by google... but then when we have translations they wont be found and indexed.
We really shouldn't be duplicating the same English content across the various languages.  It's just going to hurt our SEO for the actual articles because ranking "points" or whatever google uses will be split across multiple copies.. the more languages we have the worse it'll get.
Hugo handles everything transparently so if an article doesn't exist in ${language} it'll silently fall back to the English version. But we aren't using Hugo for our server, and nginx doesn't have that functionality.
We either need:
A) Active translators who will translate everything quickly
B) only add translated articles and leave everything else empty (this will lead to broken links)
C) When we create a new language we do a rough auto-translation just to get them started with a banner explaining that, and then hope the people who requested the translation will clean up any errors.
...or... we need to rethink our entire idea for how we are handling translations.  

And as I mentioned... as we archive different versions of the site when we do versioning... we're going to end up with exactly the same problem compounded worse, because we're archiving everything so we're going to end up with multiple copies in various stages of correctness... all competing with each other in google search algorithm.  Right now we have EN/FR versions of the same files, after we archive 11.3 for 12.0... we'll have 4. 
This problem is going to get worse not better.  There has to be a better solution than our current strategy for what we want to accomplish.  Since we are such a small team, even with community volunteers we dont have the community size that something like Kubernetes has.

**Comment by Mrt134** [comment]
Sounds like the work can't be done, so I'll go ahead and remove all translation capability from the website.

**Comment by a-stjohn** [comment]
> Sounds like the work can't be done, so I'll go ahead and remove all translation capability from the website.

So should we close this PR and continue using the lunr.js search functionality? In my opinion I think it's cleaner.

**Comment by Mrt134** [comment]
That will be up to the original requestors who complained that searching the site currently sucks. Please speak to Kris and Morgan about what is needed to improve search functionality.

**Comment by a-stjohn** [comment]
Talked to Kris and he said that it was fine to leave the current search functionality (lunr.js). Translations have been removed for now. Should be working as expected. Closing this PR.

**Pull request closed without merging**
