### PR TITLE
Tonyriv3 patch 1

### PR DESCRIPTION
**Pull request by tonyriv3**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Review by Mrt134 — CHANGES_REQUESTED** [review]
Looks like you've got leftover cruft from a previous commit in this branch and PR. Can you remove all the files related to the MinIO Clusters in SCALE article and update your PR?

**Comment by tonyriv3** [comment]
Did that work?

**Comment by Mrt134** [comment]
Almost, just need to clear out those additional image files and we should be good to go :)

**Comment by tonyriv3** [comment]
How about now?

**Comment by Mrt134** [comment]
Much better, thanks!

**Review by Mrt134 — APPROVED** [review]

**Pull request merged**
