### PR TITLE
DOCS-959-forked-repos

### PR DESCRIPTION
**Pull request by q5sys**
add header for forking section

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by kmoore134** [comment]
retest this please

**Comment by kmoore134** [comment]
retest this please

**Comment by kmoore134** [comment]
retest this please

**Comment by q5sys** [comment]
@Mrt134 Feel free to move this around if you think there's a better placement for it.

**Review by Mrt134 — APPROVED** [review]

**Pull request merged**
